import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComp from "@/components/HeaderComp";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body classNameName={inter.classNameName}>
        <HeaderComp />
        {children}
        <Footer />
      </body>
    </html>
  );
}
